config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :projects do
    resources :experiments, except: :index do
      resources :procedures, except: [:index, :show] do
        post '/observations', to: 'observations#procedure_create'
        resources :observations, except: [:index, :show, :create] do
          resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
        end
      end
      post '/observations', to: 'observations#experiment_create'
      resources :observations, except: [:index, :show, :create] do
        resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
      end
      resources :comments, except: [:index, :show, :create]
        post '/comments', to: 'comments#experiment_create'
    end
    get '/experiments/:id/conclusions', to: 'experiments#conclusions', as: 'conclusions'
    get '/experiments/:id/results', to: 'experiments#results', as: 'results'
    get '/experiments/:id/observations', to: 'experiments#observations', as: 'observations'
    get '/experiments/:id/procedures', to: 'experiments#procedures', as: 'procedures'
    resources :comments, except: [:index, :show, :create]
      post '/comments', to: 'comments#project_create'
  end

  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new' # TEMPORARY

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :position
  has_many :researcher_projects, foreign_key: :researcher_id
  has_many :created_proposals, class_name: "Project", foreign_key: :creator_id
  has_many :comments, foreign_key: :commenter_id
  has_many :experiments, foreign_key: :experimenter_id
  has_many :projects, through: :researcher_projects
  has_many :observations, through: :experiments
  has_many :procedures, through: :experiments

  has_secure_password

  validates :email, presence: true,
  									uniqueness: true,
  									length: { maximum: 255 },
  									format: { with: /\A[a-zA-Z0-9_.+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-.]+\z/ }


  def full_name
  	"#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
    @show_user = User.find_by(id: params[:id])
    @projects = Project.where(creator: @show_user)
  end

  def new
    if is_faculty?
      @new_user = User.new
    else
      render_404
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
  	if position_params
  		@new_user.position = Position.find_by(title: "faculty")
  	else
  		@new_user.position = Position.find_by(title: "staff")
  	end


    if @new_user.save
      redirect_to create_sessions_path
    else
    	render "new"
    end
  end

private
	def user_params
		params.require(:user).permit(:first_name , :last_name, :email, :password)
	end

	def position_params
		if params[:position]
			return params.require(:position).permit(:title)
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def is_faculty?
		@user.position.title == "faculty"
	end
end

app/views/users/edit.html.erb
<% provide :title, "Faculty Edit" %>
<div class="form">
  <h1>Faculty Edit</h1>
  <%= form_for @user, url: { :action => 'update' } do |f| %>
  	<%= f.label :first_name %>
  	<%= f.text_field :first_name, value: @user.first_name %><br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, value: @user.last_name %><br>

    <%= f.label :email %>
    <%= f.text_field :email, value: @user.email %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br> 

    <%= f.submit "Edit Profile" %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="form_errors">
    <% for message_error in @user.errors.full_messages %>
      <li> <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide :title, "Faculty Signup" %>
<div class="form">
  <h1>Faculty Sign Up</h1>
  <%= form_for :new_user, :url => { :controller => 'users', :action => 'create' } do |f| %>
  	<%= f.label :first_name %>
  	<p><%= f.text_field :first_name %></p>

    <%= f.label :last_name %> 
    <p><%= f.text_field :last_name %></p>

    <%= f.label :email %> 
    <p><%= f.text_field :email %></p>

    <%= f.label :password %>
    <p><%= f.password_field :password %></p>

    <%= f.label :password_confirmation %> 
    <p><%= f.password_field :password_confirmation %></p>

    <%= f.label "Faculty?" %> 
    <%= f.check_box :position %>

    <p><%= f.submit "Register Researcher" %></p>
  <% end %>
  <% if @new_user.errors.any? %>
    <ul class="form_errors">
    <% for message_error in @new_user.errors.full_messages %>
      <li> <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @show_user.full_name %>'s <%= @show_user.position.title.capitalize %> Profile</h1>

<hr>

	<% @projects.each do |project| %>
		<%= link_to "#{ project.name }", project_path %>
	<% end %>

	<hr>
<% if is_faculty?%>
	<%= link_to "Add Researcher", new_user_path %> | 
<% end %>
<%= link_to "Edit Profile", edit_user_path %>