config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :projects do
    resources :experiments, except: :index do
      resources :procedures, except: [:index, :show] do
        post '/observations', to: 'observations#procedure_create'
        resources :observations, except: [:index, :show, :create] do
          resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
        end
      end
      post '/observations', to: 'observations#experiment_create'
      resources :observations, except: [:index, :show, :create] do
        resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
      end
      resources :comments, except: [:index, :show, :create]
        post '/comments', to: 'comments#experiment_create'
    end
    get '/experiments/:id/conclusions', to: 'experiments#conclusions', as: 'conclusions'
    get '/experiments/:id/results', to: 'experiments#results', as: 'results'
    get '/experiments/:id/observations', to: 'experiments#observations', as: 'observations'
    get '/experiments/:id/procedures', to: 'experiments#procedures', as: 'procedures'
    resources :comments, except: [:index, :show, :create]
      post '/comments', to: 'comments#project_create'
  end

  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new' # TEMPORARY

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :researcher_projects
  has_many :experiments
  has_many :comments, :as => :commentable
  has_many :researchers, through: :researcher_projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    unless @user
      render_404
    end
    @projects = Project.all
  end

  def show
    unless @user
      render_404
    end
  end

  def new
    unless @user
      render_404
    end
    @project = Project.new
  end

  def create
    unless @user
      render_404
    end
    @project = Projects.build(project_params)
    @project.creator = @user

    if @project.save
      redirect_to project_path(@project)
    else
      render new_project_path
    end
  end

  def edit
    unless creator?
      render_404
    end
  end

  def update
    if creator?
      if @project.update_attributes(project_params)
        redirect_to project_path(@project)
      else
        render edit_project_path(@project)
      end
    else
      render_404
    end
  end

  def destroy
    if creator?
      @project.destory
      redirect_to root_url
    else
      render_404
    end
  end

private
  def creator?
    @user.id == @project.creator.id
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :summary, :hypothesis)
  end
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :summary %><br>
  <%= f.text_area :summary %>
  <br>
  <%= f.label :hypothesis %><br>
  <%= f.text_area :hypothesis %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<p class="title">Projects</p>

<% @projects.each do |project| %>
  <div class="listing">
    <p><%= link_to project.name, project_path(project) %></p>
    <p>Author: <%= link_to project.creator.full_name, user_path(project.creator) %>
    <p class="fineprint"><%= project.experiments.count %> experiments posted</p>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<p class="title"><%= @project.name %></p>
<p>Author: <%= link_to @project.creator.full_name, user_path(@project.creator) %><p>
<p>Hypothesis: <%= @project.hypothesis %></p>
<p>Summary: <%= @project.summary %></p>

<p class="titlesmall">Comments</p>

<% @project.comments.each do |comment| %>
  <p class="commentbody"><%= comment.content %>
    <span class="fineprint">--<%= link_to comment.commenter.full_name, user_path(comment.commenter) %>
    <%= comment.created_at.strftime(", %A, %d %b %Y %l:%M %p") %></span>
  </p>
<% end %>

<%= form_tag(new_project_comment_path(@project), id: "comment_button", method: "get") do %>
  <%= submit_tag("Add a comment") %>
<% end %>

<p class="titlesmall">Experiments</p>

<% @project.experiments.each do |experiment| %>
  <div class="listing">
    <p><%= link_to experiment.name, project_experiment_path(@project, experiment) %></p>
    <p class="fineprint"><%= experiment.created_at.strftime("Posted on %A, %d %b %Y %l:%M %p") %>
      by <%= link_to experiment.experimenter.full_name, user_path(experiment.experimenter) %>
    </p>
  </div>
<% end %>

<%= form_tag(new_project_experiment_path(@project), id: "experiment_button", method: "get") do %>
  <%= submit_tag("Add an Experiment") %>
<% end %>