config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :projects do
    resources :experiments, except: :index do
      resources :procedures, except: [:index, :show] do
        post '/observations', to: 'observations#procedure_create'
        resources :observations, except: [:index, :show, :create] do
          resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
        end
      end
      post '/observations', to: 'observations#experiment_create'
      resources :observations, except: [:index, :show, :create] do
        resources :comments, except: [:index, :show, :create]
          post '/comments', to: 'comments#observation_create'
      end
      resources :comments, except: [:index, :show, :create]
        post '/comments', to: 'comments#experiment_create'
    end
    get '/experiments/:id/conclusions', to: 'experiments#conclusions', as: 'conclusions'
    get '/experiments/:id/results', to: 'experiments#results', as: 'results'
    get '/experiments/:id/observations', to: 'experiments#observations', as: 'observations'
    get '/experiments/:id/procedures', to: 'experiments#procedures', as: 'procedures'
    resources :comments, except: [:index, :show, :create]
      post '/comments', to: 'comments#project_create'
  end

  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new' # TEMPORARY

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  belongs_to :project
  belongs_to :experimenter, class_name: "User"
  has_many :procedures
  has_many :observations, :as => :observable
  has_many :comments, :as => :commentable
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :user?
  before_action :set_experiment, except: [:new, :create]
  before_action :set_project

  def show
  end

  def conclusions
  end

  def results
  end

  def observations
  end

  def procedures
  end

  def new
    @experiment = Experiment.new
  end

  def create
    if is_staff?
      @experiment = @project.experiments.build(experiment_params)
      @experiment.experimenter = @user

      if @experiment.save
        redirect_to project_experiment_path(@project, @experiment)
      else
        render new_project_experiment_path(@project)
      end
    else
      render_404
    end
  end

  def edit
    unless experimenter?
      render_404
    end
  end

  def update
    if experimenter?
      if @experiment.update_attributes(experiment_params)
        redirect_to project_experiment_path(@project, @experiment)
      else
        render edit_project_experiment_path(@project, @experiment)
      end
    else
      render_404
    end
  end

  def destroy
    if experimenter?
      @experiment.destroy
      redirect_to project_path(@project)
    else
      render_404
    end
  end

private
  def user?
    unless @user
      render_404
    end
  end

  def is_staff?
    @user.position.title == "staff"
  end

  def set_experiment
    @experiment = Experiment.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end

  def experimenter?
    @user.id == @experiment.experimenter.id
  end

  def experiment_params
    params.require(:experiment).permit(:name, :results, :conclusion)
  end
end

app/views/experiments/_comment_button.html.erb
<%= form_tag("comment/new", id: "comment_button", method: "get") do %>
  <%= submit_tag("Add a comment") %>
<% end %>

app/views/experiments/_form.html.erb
<%= form_for [@project, @experiment] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :results %><br>
  <%= f.text_area :results %>
  <br>
  <%= f.label :conclusion %><br>
  <%= f.text_area :conclusion %>
  <%= f.submit %>
<% end %>

app/views/experiments/conclusions.html.erb
<div class="tabs">
  <ul>
    <li id="conclusions" class="active"><%= link_to "Conclusions", project_conclusions_path(@project, @experiment) %></li>
    <li id="results"><%= link_to "Results", project_results_path(@project, @experiment) %></li>
    <li id="observations"><%= link_to "Observations", project_observations_path(@project, @experiment) %></li>
    <li id="procedures"><%= link_to "Procedures", project_procedures_path(@project, @experiment) %></li>
    <li id="summary"><%= link_to "Summary", project_experiment_path(@project, @experiment) %></li>
  </ul>
</div>

<p class="title"><%= @experiment.name %></p>
<div id="experiment_content">
  <p class="title">Conclusion</p>
  <p><%= @experiment.conclusion %></p>
</div>

app/views/experiments/edit.html.erb
<h1> Edit Experiment </h1>
<%= render 'form' %>

app/views/experiments/new.html.erb
<h1> New Experiment </h1>
<%= render 'form' %>

app/views/experiments/observations.html.erb
<div class="tabs">
  <ul>
    <li id="conclusions"><%= link_to "Conclusions", project_conclusions_path(@project, @experiment) %></li>
    <li id="results"><%= link_to "Results", project_results_path(@project, @experiment) %></li>
    <li id="observations" class="active"><%= link_to "Observations", project_observations_path(@project, @experiment) %></li>
    <li id="procedures"><%= link_to "Procedures", project_procedures_path(@project, @experiment) %></li>
    <li id="summary"><%= link_to "Summary", project_experiment_path(@project, @experiment) %></li>
  </ul>
</div>

<p class="title"><%= @experiment.name %></p>
<div id="experiment_content">
  <p class="title">Observations</p>
  <% @experiment.observations.each do |observation| %>
    <p><%= observation.content %></p>
    <% observation.comments.each do |comment| %>
      <p class="commentbody"><%= comment.content %>
        <span class="fineprint">--<%= link_to comment.commenter.full_name, user_path(comment.commenter) %>
        <%= comment.created_at.strftime(", %A, %d %b %Y %l:%M %p") %></span>
      </p>
    <% end %>
  <% end %>
</div>

app/views/experiments/procedures.html.erb
<div class="tabs">
  <ul>
    <li id="conclusions"><%= link_to "Conclusions", project_conclusions_path(@project, @experiment) %></li>
    <li id="results"><%= link_to "Results", project_results_path(@project, @experiment) %></li>
    <li id="observations"><%= link_to "Observations", project_observations_path(@project, @experiment) %></li>
    <li id="procedures" class="active"><%= link_to "Procedures", project_procedures_path(@project, @experiment) %></li>
    <li id="summary"><%= link_to "Summary", project_experiment_path(@project, @experiment) %></li>
  </ul>
</div>

<p class="title"><%= @experiment.name %></p>
<div id="experiment_content">
  <p class="title">Procedures</p>

  <% @experiment.procedures.each do |procedure| %>
    <p><%= procedure.instructions %><p>

    <p class="titlesmall">Observations</p>

    <% procedure.observations.each do |observation| %>
      <p class="commentbody"><%= observation.content %></p>
      <% observation.comments.each do |comment| %>
        <p class="commentobservation"><%= comment.content %>
          <span class="fineprint">--<%= link_to comment.commenter.full_name, user_path(comment.commenter) %>
          <%= comment.created_at.strftime(", %A, %d %b %Y %l:%M %p") %></span>
        </p>
      <% end %>
    <% end %>
  <% end %>

  <%= render "comment_button" %>

</div>

app/views/experiments/results.html.erb
<div class="tabs">
  <ul>
    <li id="conclusions"><%= link_to "Conclusions", project_conclusions_path(@project, @experiment) %></li>
    <li id="results" class="active"><%= link_to "Results", project_results_path(@project, @experiment) %></li>
    <li id="observations"><%= link_to "Observations", project_observations_path(@project, @experiment) %></li>
    <li id="procedures"><%= link_to "Procedures", project_procedures_path(@project, @experiment) %></li>
    <li id="summary"><%= link_to "Summary", project_experiment_path(@project, @experiment) %></li>
  </ul>
</div>

<p class="title"><%= @experiment.name %></p>
<div id="experiment_content">
  <p class="title">Results</p>
  <p><%= @experiment.results %></p>
</div>

app/views/experiments/show.html.erb
<div class="tabs">
  <ul>
    <li id="conclusions"><%= link_to "Conclusions", project_conclusions_path(@project, @experiment) %></li>
    <li id="results"><%= link_to "Results", project_results_path(@project, @experiment) %></li>
    <li id="observations"><%= link_to "Observations", project_observations_path(@project, @experiment) %></li>
    <li id="procedures"><%= link_to "Procedures", project_procedures_path(@project, @experiment) %></li>
    <li id="summary" class="active"><%= link_to "Summary", project_experiment_path(@project, @experiment) %></li>
  </ul>
</div>

<p class="title"><%= @experiment.name %></p>
<div id="experiment_content">
  <p>Author: <%= link_to @experiment.experimenter.full_name, user_path(@experiment.experimenter) %><p>
  <p>In Response to Proposal: <%= link_to @experiment.project.name, project_path(@experiment.project) %></p>
  <p>Date: <%= @experiment.created_at.strftime("%A, %d %b %Y") %></p>

  <p class="titlesmall">Comments</p>

  <% @experiment.comments.each do |comment| %>
    <p class="commentbody"><%= comment.content %>
      <span class="fineprint">--<%= link_to comment.commenter.full_name, user_path(comment.commenter) %>
      <%= comment.created_at.strftime(", %A, %d %b %Y %l:%M %p") %></span>
    </p>
  <% end %>

  <%= render "comment_button" %>
</div>